from building import *

cwd     = GetCurrentDir()
src = ['main.c']

if GetDepend(['PKG_USING_NRF24L01']):
    src += ['nrf24l01_init.c']

CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
